[tool.poetry]
name = "rwandaphoneformat"
version = "0.1.10"
description = ""
authors = ["Jean Eric TUYISHIMIRE <ericjohn415@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
